### ISSUE TITLE
Could not open matrix file .//sub-0/T1w/sub-0/mri/transforms/T2wtoT1w.mat

### ISSUE THREAD

**Issue by soichih** [kathrynalpert/app-hcp-postfreesurfer#1]
This is probably HCPpipeline script issue, but I am seeing the following error message when I run this App.

```
+ stage=PostFreeSurfer
++ jq -r .freesurfer config.json
+ fs=testdata/freesurfer/output
++ jq -r .hcp_freesurferpre config.json
+ predat=testdata/freesurferpre/output
++ jq -r '._inputs[0].meta.subject' config.json
++ tr -d _
+ sub=null
+ [[ -z null ]]
+ [[ null == null ]]
+ sub=0
+ bids_sub=sub-0
+ cp -r testdata/freesurferpre/output sub-0
+ cp -r testdata/freesurfer/output sub-0/T1w/sub-0
+ chmod -R +w sub-0/T1w/sub-0
+ singularity exec -e docker://brainlife/hcppipeline:0.1 ./run.py input ./ participant --n_cpus 8 --stages PostFreeSurfer --license_key 'hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc' --participant_label 0
/opt/HCP-Pipelines/PostFreeSurfer/PostFreeSurferPipeline.sh --path="./" --subject="sub-0" --surfatlasdir="/opt/HCP-Pipelines/global/templates/standard_mesh_atlases" --grayordinatesdir="/opt/HCP-Pipelines/global/templates/91282_Greyordinates" --grayordinatesres="2" --hiresmesh="164" --lowresmesh="32" --subcortgraylabels="/opt/HCP-Pipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt" --freesurferlabels="/opt/HCP-Pipelines/global/config/FreeSurferAllLut.txt" --refmyelinmaps="/opt/HCP-Pipelines/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii" --regname="FS" --printcom=""
Tue Jun 16 16:20:11 UTC 2020 - PostFreeSurferPipeline.sh - Parsing Command Line Options

Tue Jun 16 16:20:12 UTC 2020 - PostFreeSurferPipeline.sh - RegName: FS

Tue Jun 16 16:20:12 UTC 2020 - PostFreeSurferPipeline.sh - Conversion of FreeSurfer Volumes and Surfaces to NIFTI and GIFTI and Create Caret Files and Registration

Tue Jun 16 16:20:12 UTC 2020 - PostFreeSurferPipeline.sh - RegName: FS



 START: FS2CaretConvertRegisterNonlinear

FreeSurfer2CaretConvertAndRegisterNonLinear.sh: RegName: FS

mri_convert -rt nearest -rl .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz .//sub-0/T1w/sub-0/mri/wmparc.mgz .//sub-0/T1w/wmparc_1mm.nii.gz 

$Id: mri_convert.c,v 1.179.2.7 2012/09/05 21:55:16 mreuter Exp $

reading from .//sub-0/T1w/sub-0/mri/wmparc.mgz...

TR=6.40, TE=0.00, TI=0.00, flip angle=0.00

i_ras = (-1, 0, 0)

j_ras = (0, 0, -1)

k_ras = (0, 1, 0)

reading template info from volume .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz...

changing data type from int to float (noscale = 0)...

Reslicing using nearest 

writing to .//sub-0/T1w/wmparc_1mm.nii.gz...



WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'



mri_convert -rt nearest -rl .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz .//sub-0/T1w/sub-0/mri/aparc.a2009s+aseg.mgz .//sub-0/T1w/aparc.a2009s+aseg_1mm.nii.gz 

$Id: mri_convert.c,v 1.179.2.7 2012/09/05 21:55:16 mreuter Exp $

reading from .//sub-0/T1w/sub-0/mri/aparc.a2009s+aseg.mgz...

TR=6.40, TE=0.00, TI=0.00, flip angle=0.00

i_ras = (-1, 0, 0)

j_ras = (0, 0, -1)

k_ras = (0, 1, 0)

reading template info from volume .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz...

changing data type from int to float (noscale = 0)...

Reslicing using nearest 

writing to .//sub-0/T1w/aparc.a2009s+aseg_1mm.nii.gz...



WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'



mri_convert -rt nearest -rl .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz .//sub-0/T1w/sub-0/mri/aparc+aseg.mgz .//sub-0/T1w/aparc+aseg_1mm.nii.gz 

$Id: mri_convert.c,v 1.179.2.7 2012/09/05 21:55:16 mreuter Exp $

reading from .//sub-0/T1w/sub-0/mri/aparc+aseg.mgz...

TR=6.40, TE=0.00, TI=0.00, flip angle=0.00

i_ras = (-1, 0, 0)

j_ras = (0, 0, -1)

k_ras = (0, 1, 0)

reading template info from volume .//sub-0/T1w/T1w_acpc_dc_restore.nii.gz...

changing data type from int to float (noscale = 0)...

Reslicing using nearest 

writing to .//sub-0/T1w/aparc+aseg_1mm.nii.gz...



WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'



parsed 'var * -1' as '(var*(-1))'

parsed 'var * -1' as '(var*(-1))'

parsed 'var * -1' as '(var*(-1))'

parsed 'abs(thickness)' as 'abs(thickness)'

parsed 'thickness > 0' as '(thickness>0)'

reading colortable from annotation file...

colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)

reading colortable from annotation file...

colortable with 76 entries read (originally Simple_surface_labels2008.txt)

parsed 'ln(spherereg / sphere) / ln(2)' as '(ln((spherereg/sphere))/ln(2))'

parsed '(atlas + individual) > 0' as '((atlas+individual)>0)'

parsed 'var * -1' as '(var*(-1))'

parsed 'var * -1' as '(var*(-1))'

parsed 'var * -1' as '(var*(-1))'

parsed 'abs(thickness)' as 'abs(thickness)'

parsed 'thickness > 0' as '(thickness>0)'

reading colortable from annotation file...

colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)

reading colortable from annotation file...

colortable with 76 entries read (originally Simple_surface_labels2008.txt)

parsed 'ln(spherereg / sphere) / ln(2)' as '(ln((spherereg/sphere))/ln(2))'

parsed '(atlas + individual) > 0' as '((atlas+individual)>0)'



 END: FS2CaretConvertRegisterNonlinear

Tue Jun 16 16:28:00 UTC 2020 - PostFreeSurferPipeline.sh - Create FreeSurfer ribbon file at full resolution



 START: CreateRibbon



WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-LH-UNKNOWN', changing one to 'CTX-LH-UNKNOWN_1'





WARNING: name collision in input name 'CTX-RH-UNKNOWN', changing one to 'CTX-RH-UNKNOWN_1'





WARNING: name collision in input name 'WM-LH-UNKNOWN', changing one to 'WM-LH-UNKNOWN_1'





WARNING: name collision in input name 'WM-RH-UNKNOWN', changing one to 'WM-RH-UNKNOWN_1'





 END: CreateRibbon

Tue Jun 16 16:30:47 UTC 2020 - PostFreeSurferPipeline.sh - Myelin Mapping

Tue Jun 16 16:30:47 UTC 2020 - PostFreeSurferPipeline.sh - RegName: FS



 START: CreateMyelinMaps

CreateMyelinMaps.sh: RegName: FS

Could not open matrix file .//sub-0/T1w/sub-0/mri/transforms/T2wtoT1w.mat

terminate called after throwing an instance of 'NEWMAT::IncompatibleDimensionsException'

/opt/HCP-Pipelines/PostFreeSurfer/scripts/CreateMyelinMaps.sh: line 61: 28743 Aborted                 (core dumped) convertwarp --relout --rel --ref="$T1wImageBrain" --premat="$InitialT2wTransform" --warp1="$dcT2wTransform" --postmat="$FinalT2wTransform" --out="$OutputOrigT2wToT1w"


Traceback (most recent call last):
  File "./run.py", line 356, in <module>
    stage_func()
  File "./run.py", line 113, in run_post_freesurfer
    run(cmd, cwd=args["path"], env={"OMP_NUM_THREADS": str(args["n_cpus"])})
  File "./run.py", line 29, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 134
You have new mail in /var/mail/hayashis
```

@kathrynalpert I am not sure if you are still available to troubleshoot these issues. Please let me know if you'd like us to move this repo under brainlife/ org.

**Comment by radiologics-kate** [comment]
Looks like an issue with the data itself - invalid or missing file. Have you tried running on data for which it previously succeeded? Happy to transfer the repo.

**Comment by kathrynalpert** [comment]
Looks like an issue with the data itself - invalid or missing file. Have you tried running on data for which it previously succeeded? Happy to transfer the repo.

**Comment by soichih** [comment]
Ok I will run a few more tests and see how it goes. It's really up to you to transfer the repo, but if you could transfer it to "brainlife" org, we can maintain the app - unless you'd like to keep maintaining it.

**Comment by soichih** [comment]
It looks like the issue is that, I have to feed freesurfer output from freesurfer v5? I believe "HCP Pipeline (Freesurfer)"(https://brainlife.io/app/5aabcf10f0b5260027e24ac8) uses freesurfer v5..?

**Comment by kathrynalpert** [comment]
Sounds right, likely HCP FS was v5 when the image was built. I am happy to transfer these repos to brainlife for continued updating and maintenance. I'll just need permissions to create repos there (temporarily).

**Comment by soichih** [comment]
OK I've sent you an invite.. I think.
